before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y libxml2-dev
    - sudo apt-get install autoconf automake autopoint bash bison bzip2 flex gettext git g++ gperf intltool libffi-dev libgdk-pixbuf2.0-dev libtool libltdl-dev libssl-dev libxml-parser-perl make openssl p7zip-full patch perl pkg-config python ruby scons sed unzip wget xz-utils
    - git clone https://github.com/mxe/mxe.git
    - export PATH=$PATH:$PWD/mxe
    - cd $PWD/mxe ; MXE_TARGETS='x86_64-w64-mingw32.static i686-w64-mingw32.static' make gcc
script:
    ./DLL\ Solution/build.sh
notifications:
    email: false
